export type EntityState = 'idle' | 'patrol' | 'alert' | 'chase' | 'attack' | 'return';

export interface EntityDef {
  id: string;
  name: string;
  entityNumber: number;
  speed: number;
  chaseSpeed: number;
  detectionRadius: number;
  hearingRadius: number;
  visionAngle: number;
  damage: number;
  hp: number;
  color: string;
  emissive: string;
  emissiveIntensity: number;
  shape: 'sphere' | 'box' | 'cylinder' | 'cone';
  scale: [number, number, number];
  hostile: boolean;
  description: string;
}

export const ENTITIES: Record<string, EntityDef> = {
  smiler: {
    id: 'smiler',
    name: '笑魇',
    entityNumber: 3,
    speed: 1.5,
    chaseSpeed: 5,
    detectionRadius: 12,
    hearingRadius: 8,
    visionAngle: 90,
    damage: 35,
    hp: 40,
    color: '#0a0a0a',
    emissive: '#ffff00',
    emissiveIntensity: 2,
    shape: 'sphere',
    scale: [0.4, 0.4, 0.4],
    hostile: true,
    description: '黑暗中发光的眼睛，切勿靠近。',
  },
  hound: {
    id: 'hound',
    name: '猎犬',
    entityNumber: 8,
    speed: 2.5,
    chaseSpeed: 7,
    detectionRadius: 15,
    hearingRadius: 20,
    visionAngle: 120,
    damage: 25,
    hp: 60,
    color: '#2a2020',
    emissive: '#ff3300',
    emissiveIntensity: 0.5,
    shape: 'box',
    scale: [0.6, 0.5, 1.2],
    hostile: true,
    description: '快速的四足生物，极度依赖听觉。',
  },
  facelings: {
    id: 'facelings',
    name: '无面灵',
    entityNumber: 9,
    speed: 1,
    chaseSpeed: 2,
    detectionRadius: 6,
    hearingRadius: 4,
    visionAngle: 60,
    damage: 10,
    hp: 20,
    color: '#c8b090',
    emissive: '#000000',
    emissiveIntensity: 0,
    shape: 'cylinder',
    scale: [0.3, 1.6, 0.3],
    hostile: false,
    description: '没有五官的人形生物，头部光滑。',
  },
  'skin-stealer': {
    id: 'skin-stealer',
    name: '窃皮者',
    entityNumber: 10,
    speed: 0.5,
    chaseSpeed: 6,
    detectionRadius: 10,
    hearingRadius: 5,
    visionAngle: 180,
    damage: 45,
    hp: 80,
    color: '#8a6050',
    emissive: '#ff6600',
    emissiveIntensity: 0.3,
    shape: 'cylinder',
    scale: [0.35, 1.7, 0.35],
    hostile: true,
    description: '皮肤拉伸的高大人形，四肢细长，双眼泛橙光。',
  },
  wretches: {
    id: 'wretches',
    name: '可怜人',
    entityNumber: 15,
    speed: 0.8,
    chaseSpeed: 2.5,
    detectionRadius: 8,
    hearingRadius: 6,
    visionAngle: 90,
    damage: 15,
    hp: 25,
    color: '#3a3a2a',
    emissive: '#444400',
    emissiveIntensity: 0.2,
    shape: 'sphere',
    scale: [0.5, 0.5, 0.5],
    hostile: true,
    description: '佝偻瘦弱的人形，双臂拖地，皮肤苍白泛黄。',
  },
// ENTITY_CONTINUE
  crawlers: {
    id: 'crawlers',
    name: '爬行者',
    entityNumber: 17,
    speed: 2,
    chaseSpeed: 5.5,
    detectionRadius: 6,
    hearingRadius: 3,
    visionAngle: 45,
    damage: 30,
    hp: 35,
    color: '#1a1a1a',
    emissive: '#880000',
    emissiveIntensity: 0.8,
    shape: 'box',
    scale: [0.8, 0.2, 0.8],
    hostile: true,
    description: '天花板上扁平的黑色物体，细腿支撑，独眼泛红。',
  },
  dullers: {
    id: 'dullers',
    name: '钝人',
    entityNumber: 6,
    speed: 0.5,
    chaseSpeed: 1,
    detectionRadius: 5,
    hearingRadius: 3,
    visionAngle: 360,
    damage: 5,
    hp: 50,
    color: '#606060',
    emissive: '#404040',
    emissiveIntensity: 0.1,
    shape: 'cylinder',
    scale: [0.4, 1.5, 0.4],
    hostile: true,
    description: '灰色无特征人形，散发迟钝气息。',
  },
  partygoers: {
    id: 'partygoers',
    name: '派对客',
    entityNumber: 67,
    speed: 1.2,
    chaseSpeed: 4,
    detectionRadius: 14,
    hearingRadius: 10,
    visionAngle: 120,
    damage: 40,
    hp: 55,
    color: '#ffee00',
    emissive: '#ffee00',
    emissiveIntensity: 1,
    shape: 'cylinder',
    scale: [0.3, 1.6, 0.3],
    hostile: true,
    description: '鲜黄色人形，咧嘴笑、戴派对帽，看似友好实则致命。',
  },
  'death-rats': {
    id: 'death-rats',
    name: '死亡鼠',
    entityNumber: 24,
    speed: 3,
    chaseSpeed: 5,
    detectionRadius: 7,
    hearingRadius: 12,
    visionAngle: 180,
    damage: 8,
    hp: 10,
    color: '#2a2020',
    emissive: '#ff0000',
    emissiveIntensity: 0.4,
    shape: 'sphere',
    scale: [0.2, 0.15, 0.3],
    hostile: true,
    description: '小型黑色啮齿动物，红眼发光，尾巴无毛。',
  },
// ENTITY_CONTINUE_2
  deathmoths: {
    id: 'deathmoths',
    name: '死亡蛾',
    entityNumber: 4,
    speed: 2,
    chaseSpeed: 3.5,
    detectionRadius: 10,
    hearingRadius: 5,
    visionAngle: 360,
    damage: 12,
    hp: 15,
    color: '#8a7a60',
    emissive: '#aa8844',
    emissiveIntensity: 0.3,
    shape: 'cone',
    scale: [0.5, 0.3, 0.5],
    hostile: true,
    description: '大型飞蛾，棕色翅膀沾尘，琥珀色眼睛发光。',
  },
  jerry: {
    id: 'jerry',
    name: '杰瑞',
    entityNumber: 7,
    speed: 0.8,
    chaseSpeed: 0.8,
    detectionRadius: 8,
    hearingRadius: 6,
    visionAngle: 120,
    damage: 0,
    hp: 999,
    color: '#5588aa',
    emissive: '#3366aa',
    emissiveIntensity: 0.5,
    shape: 'cylinder',
    scale: [0.3, 1.5, 0.3],
    hostile: false,
    description: '友好的蓝色人形，穿着休闲，为你提供指引。',
  },
  clumps: {
    id: 'clumps',
    name: '肉团',
    entityNumber: 5,
    speed: 0.3,
    chaseSpeed: 1.5,
    detectionRadius: 4,
    hearingRadius: 6,
    visionAngle: 360,
    damage: 20,
    hp: 70,
    color: '#5a3030',
    emissive: '#330000',
    emissiveIntensity: 0.2,
    shape: 'sphere',
    scale: [0.6, 0.6, 0.6],
    hostile: true,
    description: '纠缠的肢体与血肉团，悬挂在狭小空间，多条手臂外伸。',
  },
  windows: {
    id: 'windows',
    name: '窗户',
    entityNumber: 2,
    speed: 0,
    chaseSpeed: 0,
    detectionRadius: 6,
    hearingRadius: 3,
    visionAngle: 180,
    damage: 30,
    hp: 100,
    color: '#2a3a4a',
    emissive: '#4488cc',
    emissiveIntensity: 0.6,
    shape: 'box',
    scale: [0.8, 1.2, 0.1],
    hostile: true,
    description: '嵌入墙中的有知觉窗框，泛着敌意的蓝光，靠近会攻击。',
  },
};